package com.example.harmonie_budget_app_kt.models

/**
 * Expense model representing a single expense record.
 * This data class contains all fields required by the assignment specification.
 *
 * Part 3 Enhancement:
 * The model includes all required fields for the expense history table:
 * - Amount: The monetary value of the expense (Double)
 * - Date: The date of the expense in yyyy-MM-dd format (String)
 * - Start Time: The start time of the expense in HH:mm format (String)
 * - End Time: The end time of the expense in HH:mm format (String)
 * - Description: A textual description of the expense (String)
 * - Category ID: The identifier linking to a Category object (Int)
 * - Photo URI: An optional URI string pointing to an attached photo (String? = null)
 *
 * Note: The id field is auto-generated by JsonHelper.saveExpense.
 * The submission time is not stored permanently because it is derived from
 * the system time when the expense is saved. For display purposes, the
 * submission time is generated at runtime.
 *
 * Gson handles serialization automatically. All fields are included in the
 * JSON representation because the default Gson behavior includes all properties.
 *
 * @param id Unique identifier for the expense (auto-generated, starting from 1)
 * @param amount The monetary amount spent (must be a positive number, validated in UI)
 * @param date The date of the expense in yyyy-MM-dd format
 * @param startTime The start time of the expense in HH:mm format
 * @param endTime The end time of the expense in HH:mm format
 * @param description A textual description of the expense
 * @param categoryId The ID of the category this expense belongs to
 * @param photoUri An optional URI string pointing to an attached receipt photo
 */
data class Expense
    (
    val id: Int,
    val amount: Double,
    val date: String,
    val startTime: String,
    val endTime: String,
    val description: String,
    val categoryId: Int,
    val photoUri: String? = null
)